version: "3.9"

services:
  overv:
    image: overv/openstreetmap-tile-server:latest
    restart: always
    ports:
      - "${OSM_PORT:-8080}:80"
    volumes:
      - ./overv/database:/var/lib/postgresql/15/main
      - ./overv/style:/data/style
      - ./overv/data:/data
    command: run
    env_file:
      - .env
    networks:
      - app-network

  osrm-backend:
    image: osrm/osrm-backend:latest
    restart: always
    ports:
      - "${OSRM_PORT:-5000}:5000"
    volumes:
      - ./overv/data/region.osm.pbf:/data/region.osm.pbf
    command: >
      /bin/bash -c "
      if [ ! -f /data/region.osrm ]; then
        osrm-extract -p /opt/car.lua /data/region.osm.pbf &&
        osrm-partition /data/region.osrm &&
        osrm-customize /data/region.osrm;
      fi &&
      osrm-routed --algorithm mld /data/region.osrm"
    env_file:
      - .env
    networks:
      - app-network

  nominatim:
    image: mediagis/nominatim:4.3
    restart: always
    volumes:
      - nominatim-data:/var/lib/postgresql/12/main
      - ./overv/data:/data
    ports:
      - "${NOMINATIMUS_PORT:-7070}:8080"
    environment:
      PBF_PATH: /data/region.osm.pbf
      NOMINATIM_THREADS: 4
      NOMINATIM_IMPORT: "true"
    env_file:
      - .env
    networks:
      - app-network

volumes:
  nominatim-data:

networks:
  app-network:
    driver: bridge
